### ISSUE TITLE
Vagueness about getting started with CLI

### ISSUE THREAD

**Issue by ThatBeardedDude** [radanalyticsio/oshinko-cli#111]
As a user I feel lost when I try to follow the README. From the get go I get errors about missing build file and I don't understand where should I posistion myself to start working with the CLI.
I have already set up a working webui and worked with it so the infrastructure seems to work. 
What am I doing wrong?
Can anyone help lead me to the enterence?

**Comment by ThatBeardedDude** [comment]
I've figured out where to place myself to start working . 
Closing this issue but openning a new one regarding the making of a clearer README.md

**Comment by elmiko** [comment]
yeah, we've got some work to do here. are you looking to start using the cli or do you want to contribute to the code?

**Comment by ThatBeardedDude** [comment]
I'd love contributing once I've got everything up and running. 
Some ideas come to mind (though most are features focused on the webui) and this project fits my needs perfectly so it's a win win I think

**Comment by elmiko** [comment]
so, yeah, as you noticed we need to update the readme but if you'd like to start using the cli i would recommend getting one of the release tars as they have precompiled binaries for linux32/64 and osx (hopefully one of those will work for you!)

**Comment by elmiko** [comment]
i would start with this one, https://github.com/radanalyticsio/oshinko-cli/releases/tag/v0.4.6

**Comment by elmiko** [comment]
one more note about building, and this should probably be in the readme, oshinko-cli is a go program. so in order for the `make build` command to work, you will need to have the Go language compiler installed and you will need to have the `oshinko-cli` project directory in the proper place on your go path. somewhere like `${GOPATH}/src/github.com/radanalyticsio/oshinko-cli`, then the make should work. good luck!

**Comment by ThatBeardedDude** [comment]
Thanks a lot for the help!
I got the cli working with the url you sent (v0.4.6)!
BTW after I downloaded go lang, when building I get this (hilarious) error: 
[FATAL] Detected Go version: go version go1.10.1 linux/amd64.
[FATAL] Builds require Go version go1.9 or greater.

**Comment by elmiko** [comment]
wow, that is a really special error. looks like we have some testing to do!

**Comment by rebeccaSimmonds19** [comment]
#123
