### ISSUE TITLE
Unable to build binary for oshinko-cli with mac os x

### ISSUE THREAD

**Issue by padrian2s** [radanalyticsio/oshinko-cli#122]
$make build
scripts/build.sh build
cmd/oshinko/oshinko.go:11:2: cannot find package "github.com/radanalyticsio/oshinko-cli/pkg/cmd/cli" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/radanalyticsio/oshinko-cli/pkg/cmd/cli (from $GOROOT)
	/Users/p3/go/src/github.com/radanalyticsio/oshinko-cli/pkg/cmd/cli (from $GOPATH)
cmd/oshinko/oshinko.go:9:2: cannot find package "k8s.io/apiserver/pkg/util/logs" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/k8s.io/apiserver/pkg/util/logs (from $GOROOT)
	/Users/p3/go/src/k8s.io/apiserver/pkg/util/logs (from $GOPATH)
cmd/oshinko/oshinko.go:14:2: cannot find package "k8s.io/kubernetes/pkg/apis/autoscaling/install" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/k8s.io/kubernetes/pkg/apis/autoscaling/install (from $GOROOT)
	/Users/p3/go/src/k8s.io/kubernetes/pkg/apis/autoscaling/install (from $GOPATH)
cmd/oshinko/oshinko.go:15:2: cannot find package "k8s.io/kubernetes/pkg/apis/batch/install" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/k8s.io/kubernetes/pkg/apis/batch/install (from $GOROOT)
	/Users/p3/go/src/k8s.io/kubernetes/pkg/apis/batch/install (from $GOPATH)
cmd/oshinko/oshinko.go:13:2: cannot find package "k8s.io/kubernetes/pkg/apis/core/install" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/k8s.io/kubernetes/pkg/apis/core/install (from $GOROOT)
	/Users/p3/go/src/k8s.io/kubernetes/pkg/apis/core/install (from $GOPATH)
cmd/oshinko/oshinko.go:16:2: cannot find package "k8s.io/kubernetes/pkg/apis/extensions/install" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/k8s.io/kubernetes/pkg/apis/extensions/install (from $GOROOT)
	/Users/p3/go/src/k8s.io/kubernetes/pkg/apis/extensions/install (from $GOPATH)

first bump with openshift so far :(

**Comment by rebeccaSimmonds19** [comment]
@padrian2s, hi there, have you made sure you have set your $GOPATH, this will be the folder go/src where you need to add all of your code. The directory structure of your code also need to be: /go/src/github.com/radanalyticsio/oshinko-cli, where oshinko cli is the cloned repo. Also make sure you have a cluster up and that you have installed coreutils (described in the readme). I hope this helps the readme.md will hopefully reflect these instructions soon i have made a PR. If you have anymore trouble please reply to this comment if not i will close the issue.

**Comment by padrian2s** [comment]
@rebeccaSimmonds19, Hi there, it's working! 🥇 please close the issue once the readme is updated (?).

**Comment by rebeccaSimmonds19** [comment]
That's great news thank you for your comment :) it helped pushed the priority. I hope you enjoy using oshinko.
