### ISSUE TITLE
masterWebRoute parameter returns a route value without "https://" text in oshinko get clusterName -o json

### ISSUE THREAD

**Issue by olegvn88** [radanalyticsio/oshinko-cli#131]
MasterWebRoute parameter returns route value without "https://" text in `oshinko get clusterName -o json`. Take a look at the screen shot.
We can observe that "Master Web UI" parameter contains route value with http:// on the Oshinko Spark Cluster Management page
![oshinko_cli](https://user-images.githubusercontent.com/20247663/44992250-65f4c100-af9f-11e8-8e1d-89bd289e0135.png)
![oshinko_webui](https://user-images.githubusercontent.com/20247663/44992260-6f7e2900-af9f-11e8-9c2e-14c3a7bac04c.png)

**Comment by rebeccaSimmonds19** [comment]
PR #133 fixes this
