### ISSUE TITLE
Wrong JSON/YAML output on get command

### ISSUE THREAD

**Issue by zroubalik** [radanalyticsio/oshinko-cli#44]
If I perform get command without specifying cluster name and want JSON or YAML output, I get wrong result.  Some properties are missing: "namespace", "masterCount";  some are wrong: "Config.masterCount", "Config.workerCount"; "Pods" are even null. If I perform get command and specify cluster's name, I get correct results.

**Steps to reproduce:**

1. create cluster mycluster
2. compare output of "oshinko-cli get mycluster -o json" vs. "oshinko-cli get -o json", 
eg. here:
$ oshinko-cli get mycluster -o json  output: [https://pastebin.com/BEQV6fuU](https://pastebin.com/BEQV6fuU)            
vs.
$ oshinko-cli get -o json  output: [https://pastebin.com/8i5wXa4c](https://pastebin.com/8i5wXa4c)

**Comment by sub-mod** [comment]
@zroubalik thanks looking into it

**Comment by tmckayus** [comment]
Currently, the only difference is that the pod list is left out when getting all clusters versus a single cluster. This is intentional. Closing this.
