### ISSUE TITLE
Get command on empty clusters list with JSON/YAML

### ISSUE THREAD

**Issue by zroubalik** [radanalyticsio/oshinko-cli#45]
I suggest that `oshinko-cli get -o json` command on empty clusters list should return empty JSON array `[]` instead of message `There are no clusters in any projects. You can create a cluster with the 'create' command.` 

If user specifies name of cluster which doesn't exist (eg. `oshinko-cli get nonexistingcluster - o json`), JSON output should be empty JSON object `{}` instead of `error: no such cluster 'nonexistingcluster'`

User is expecting JSON output because he has specified this type of output and may consume it in some automation/scripts.

The same should be implemented for YAML output.

**Comment by sub-mod** [comment]
@zroubalik thanks looking into it
