### ISSUE TITLE
Different output on get/list clusters operations while creating a new cluster

### ISSUE THREAD

**Issue by zroubalik** [radanalyticsio/oshinko-cli#48]
When I'm in the process of creating a new cluster and immediately run get operation with the cluster's name, the cluster is listed in the output, if I run list clusters operation (get without cluster's name), the cluster is not listed in the output (it is listed there once all workers are up).

I'm not sure if this is intentional or it is a bug.

`$ oshinko-cli create mycluster --workers=3`
`cluster "mycluster" created`
`$ oshinko-cli get mycluster`
`mycluster         0       spark://mycluster:7077          http://mycluster-ui:8080        Running`  

vs.

`$ oshinko-cli create mycluster --workers=3`
`cluster "mycluster" created`
`$ oshinko-cli get`
`There are no clusters in any projects. You can create a cluster with the 'create' command.`

**Comment by tmckayus** [comment]
Seems to not be a current issue
