### ISSUE TITLE
rest client tests need to be added to the travis configuration

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-cli#55]
currently the rest unit tests are being run by travis but not the functional client tests. normally when running these tests i would execute something akin to `oshinko-test.sh -t client -r https://github.com/elmiko/oshinko-cli -b my-feature-branch` from a shell with a logged in `oc` command on the `PATH`. this would create the necessary kubernetes/openshift objects to pull the code from my repository and build the testing rest server based the named branch. with this built as an image inside openshift, the pod would be launched and all tests are automated through the testing server.

i'm not sure how this will work under the travis setup, but if we are starting an openshift cluster it should be possible to instruct it on how to build and run our test image.

**Comment by tmckayus** [comment]
This was added with an "oshinko-test.sh -t client-local" capability
