### ISSUE TITLE
Inform the user that she can run the oshinko-rest-server on http

### ISSUE THREAD

**Issue by Jiri-Kremser** [radanalyticsio/oshinko-cli#67]
Currently, if I run the `oshinko-rest-server` it prints:

```bash
oshinko-rest-server 
2017/09/06 16:00:42 Starting oshinko-rest-server version v0.2.5
2017/09/06 16:00:42 the required flags `--tls-certificate` and `--tls-key` were not specified
```

I am new a user trying oshinko. Ok they want me to create a certificate in the pem format, I am running away ;)

Perhaps it would be nice to say that it's possible to run it w/o the SSL by simple `oshinko-rest-server --scheme http`. I know, it's in the readme, but the binary should be self-explanatory too.

**Comment by rebeccaSimmonds19** [comment]
PR #128 solved this
