### ISSUE TITLE
Rename core constructor functions

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-cli#95]
To make these functions clearer to new developer, we should rename them to be more accurate about their functionality.

For example, in `core/containers/containers.go`, we could change this signature `func Container(name, image string) *OContainer` to `func NewOContainer(name, image string) *OContainer` to be more explicit.

migrated from https://github.com/radanalyticsio/oshinko-rest/issues/64

**Comment by rebeccaSimmonds19** [comment]
PR #129 fixes this
